CREATE DATABASE IF NOT EXISTS test;
CREATE TABLE IF NOT EXISTS test.USER (
  ID          INT(8)      NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(25) NOT NULL,
  AGE         INT         NOT NULL,
  ISADMIN     BIT         NOT NULL DEFAULT 0,
  CREATEDDATE TIMESTAMP   NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

INSERT INTO TEST.USER (ID, NAME, AGE, ISADMIN, CREATEDDATE) VALUES
  ('1', 'ANDREW', 35, 1, '2017.02.17'),
  ('2', 'BOGDAN', 33, 0, '2017.01.17'),
  ('3', 'CINTIA', 22, 0, '2017.02.10'),
  ('4', 'DANA', 25, 0, '2016.02.10');